# Redirect to e1w subdirectory for GitHub Pages
source: e1w
destination: _site

# Include the main Gemfile for dependencies
plugins:
  - jekyll-remote-theme

# This allows GitHub Pages to build from the e1w subdirectory
include: ["e1w"]
