# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Deploy Jekyll site to GitHub Pages in e1w subdirectory

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # Build and deploy job
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true
          
      - name: Install dependencies
        run: |
          bundle config set --local deployment false
          bundle install
        
      - name: Build Jekyll site
        run: bundle exec jekyll build --source e1w --destination _site_temp
        env:
          JEKYLL_ENV: production
          
      - name: Create deployment structure
        run: |
          mkdir -p _site/e1w
          cp -r _site_temp/* _site/e1w/
          echo '<meta http-equiv="refresh" content="0; url=/e1w/">' > _site/index.html
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}e1w/
    runs-on: ubuntu-latest
    needs: build-and-deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
